version: "3.9"

services:
    site:
        build: .
        image: conjurer/faster-flow-framework.com:latest
        command: bundle exec jekyll serve --trace --host 0.0.0.0 --watch --incremental --port 4007
        environment:
            - JEKYLL_ENV=development
        volumes:
            - ./:/srv/jekyll
        ports:
            - 4006:4006
